Allow forward declarations to be used for typedefs
borglab/wrap pull request #104
Opened 2021-06-04 15:33 UTC by varunagrawal

This PR will allow us to use `typedef`s on classes defined in other projects.

E.g. GTSAM has a `ManifoldEvaluationFactor` which takes `RigidBodyState` as a template argument which is defined in DoubleExpresso.

Now in DoubleExpresso, we can do
```cpp
class gtsam::ManifoldEvaluationFactor;  // forward declare class so we can typedef

typedef gtsam::ManifoldEvaluationFactor<gtsam::Chebyshev2,
                                        gtsam::RigidBodyState>
    ManifoldEvaluationFactorChebyshev2RigidBodyState;
```

and everything should work.

2021-06-04 16:05 UTC, ProfFan requested changes
I think you should also change the integration tests (and make sure that MATLAB still works). Otherwise this looks good.

2021-06-08 03:55 UTC, varunagrawal commented
I am not sure how to test this out. The idea is to have 2 different projects so that would need some CMake related stuff happening. Any suggestions?

2021-06-08 14:56 UTC, ProfFan commented
I mean just add a forward declaration in the test header with a class that uses such a class (and regenerate the expected-python directory.

2021-06-08 20:47 UTC, ProfFan approved these changes
Awesome

2021-06-09 16:39 UTC, merged